# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyHelp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyHelp

    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'

  target 'EasyHelpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EasyHelpUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
