# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'EasyHelp Dev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyHelp

    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON', '~> 4.2.0'

    target 'EasyHelp Local' do
        inherit! :complete
    end
    
    
    target 'EasyHelp Mock' do
        inherit! :complete
    end
    
    target 'EasyHelpUITests' do
        # Pods for testing
    end

end
